### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [39]:
import numpy as np
import pandas as pd


###### 1. Write a NumPy program to find the missing data in a given array.

In [2]:
### code here
array = np.array([[3,2,'nan',1],[10,12,10,9],[5,'nan',1,'nan']])
print(array)
np.where(array=='nan','True','False')

[['3' '2' 'nan' '1']
 ['10' '12' '10' '9']
 ['5' 'nan' '1' 'nan']]


array([['False', 'False', 'True', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'True', 'False', 'True']], dtype='<U5')

In [3]:
## sample output

##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [6]:
### code here 
A1= np.arange(0,4).reshape(2,2)
A2 = np.arange(0,4).reshape(2,2)
Array = np.array_equal(A1,A2)
print(Array)


True


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [8]:
## code here
array = np.arange(0,16).reshape(4,4)
print(array)
array[[0,-1],:]=array[[-1,0],:]
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [15]:
## code here
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [11]:
#### code here
a=[1,2,3,4]
b=(3,4,5,6)
arr1=np.array(a)
print(arr1)
arr2=np.array(b)
print(arr2)


[1 2 3 4]
[3 4 5 6]


###### 5. Write a NumPy program to find common values between two arrays.

In [21]:
### code here
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(6,15).reshape(3,3)
print(np.intersect1d(arr1,arr2))
print(arr1[np.isin(arr1,arr2)])

[6 7 8 9]
[6 7 8 9]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [23]:
### code here
arr=np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
### sample output
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [47]:
### code here
arr=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
arr
a,b= np.unique(arr,return_counts=True)
print(a,'\n',b)

[10 20 30 40 50] 
 [3 4 2 2 1]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [48]:
### code here
arr1= np.array([[0,0,0],[1,2,3],[4,5,6]])
arr2= np.array([10,11,12])
np.add(arr1,arr2)

array([[10, 11, 12],
       [11, 13, 15],
       [14, 16, 18]])

In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [49]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [55]:
## code here
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print([arr[0][2],arr[0][3]])
print([arr[1][2],arr[1][3]])


[2, 3]
[6, 7]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [57]:
### code here
Today = np.datetime64("today","D")
Tomorrow = Today+1
Yesterday = Today-1
print('Today:',Today)
print('Tomorrow:',Tomorrow)
print('Yesterday:',Yesterday)

Today: 2023-01-06
Tomorrow: 2023-01-07
Yesterday: 2023-01-05


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [66]:
## code here
arr=np.busday_offset('2017-05',0,weekmask='Mon')
arr

numpy.datetime64('2017-05-01')

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
